package doyenm.zooshell.errorhandling;

public enum ErrorType {
    ALREADY_PRESENT_FACILITY,
    INADEQUATE_CONTRACEPTION,
    INCORRECT_DIMENSIONS,
    INCORRECT_HORIZON,
    INCORRECT_LOCATION,
    INCORRECT_NAME,
    NO_ENTRY,
    NOT_EMPTY_PADDOCK,
    NOT_PRESENT_FACILITY,
    UNKNOWN_ANIMAL,
    UNKNOWN_BIOME,
    UNKNOWN_CONTRACEPTION,
    UNKNOWN_PADDOCK,
    UNKNOWN_PADDOCK_FACILITY,
    UNKNOWN_PADDOCK_TYPE;
}
