package doyenm.zooshell.errorhandling;

public enum ErrorType {
    INCORRECT_DIMENSIONS,
    INCORRECT_HORIZON,
    INCORRECT_LOCATION,
    INCORRECT_NAME,
    NO_ENTRY,
    NOT_EMPTY_PADDOCK,
    UNKNOWN_BIOME,
    UNKNOWN_PADDOCK,
    UNKNOWN_PADDOCK_FACILITY,
    UNKNOWN_PADDOCK_TYPE;
}
